import SidebarNoHeader from "@/components/layout/Sidebar-Without-Header";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				{/* <main className='grid-rows-header grid min-h-screen bg-zinc-100'>
					<Layout>{children}</Layout>
				</main> */}
				<main className='flex'>
					<SidebarNoHeader />
					<div className='ml-14 flex-1 md:ml-40'>{children}</div>
				</main>
				<Toaster />
			</body>
		</html>
	);
}
